language: c

os:
  - osx

osx_image: xcode7

compiler:
  - clang

env:
  - FEATURES=huge
    VERSIONER_PERL_VERSION=5.16
    VERSIONER_PYTHON_VERSION=2.7
    vi_cv_path_python3=/usr/local/bin/python3
    vi_cv_path_plain_lua=/usr/local/bin/lua-5.1
    "CONFOPT='--with-features=huge --enable-multibyte --enable-netbeans --with-tlib=ncurses --enable-cscope --enable-perlinterp=dynamic --enable-pythoninterp=dynamic --enable-python3interp=dynamic --enable-rubyinterp=dynamic --with-ruby-command=/usr/bin/ruby --enable-ruby19interp=dynamic --with-ruby19-command=/usr/local/bin/ruby --enable-luainterp=dynamic --with-lua-prefix=/usr/local --enable-lua52interp=dynamic --with-lua52-prefix=/usr/local --enable-gui=macvim'"

sudo: false

branches:
  except:
    - /^v[0-9]/
    - kaoriya

before_install:
  - brew update
  - brew install lua51
  - brew install lua
  - brew install python3
  - brew install ruby
  - brew tap splhack/splhack
  - brew install --HEAD cmigemo-mk --with-binary-release
  - brew install gettext-mk --with-binary-release

script:
  - NPROC=$(getconf _NPROCESSORS_ONLN)
  - ./configure --with-features=$FEATURES $CONFOPT
  - make -C src/po MSGFMT=`find /usr/local/Cellar/gettext-mk -name msgfmt`
  - make -j$NPROC
  - ./src/vim --version
  - make test
  - echo $?

# vim:set sts=2 sw=2 tw=0 et:
