language: c

os:
  - osx

osx_image: xcode7

compiler:
  - clang

env:
  - FEATURES=huge
    vi_cv_path_python3=/usr/local/bin/python3
    vi_cv_path_plain_lua=/usr/local/bin/lua-5.1
    "CONFOPT='--enable-perlinterp --enable-pythoninterp --enable-python3interp --enable-rubyinterp --enable-luainterp --with-lua-prefix=/usr/local --enable-multibyte --enable-cscope --enable-netbeans --enable-gui=macvim'"

sudo: false

branches:
  except:
    - /^v[0-9]/

before_install:
  - brew update
  - brew install python3
  - brew install lua51

script:
  - NPROC=$(getconf _NPROCESSORS_ONLN)
  - ./configure --with-features=$FEATURES $CONFOPT --enable-fail-if-missing && make -j$NPROC
  - ./src/vim --version
  - make test

# vim:set sts=2 sw=2 tw=0 et:
